### ISSUE TITLE
Proper usecase

### ISSUE THREAD

**Issue by JoeyHengst** [NathanaelA/nativescript-platform-css#3]
What's the proper usecase to get this to work in Ng2?

app.module.ts
require( "nativescript-platform-css" );

login.ios.css
.ios320 .someClass{
    color:red;
}

Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 2.5.4           │ 2.5.4          │ Up to date  │
│ tns-core-modules │ 2.5.2           │ 2.5.2          │ Up to date  │
│ tns-android      │ 2.5.0           │ 2.5.0          │ Up to date  │
│ tns-ios          │ 2.5.0           │ 2.5.0          │ Up to date

Doesn't seem to work.

**Comment by NathanaelA** [comment]
@StudderVOF - I have not tested this at all in Angular apps; in fact I would guess this doesn't work in Angular because Angular builds the css with addition qualifiers that probably breaks how this plugin works in most cases; I think it could be made to work with angular; but I have not spent any time to do so.

**Comment by NathanaelA** [comment]
@studdervof - I have figured out how to make it work properly in Angular; see the docs.  ;-)
