### ISSUE TITLE
TypeError: nsPlatform.screen is not a function

### ISSUE THREAD

**Issue by felix-idf** [NathanaelA/nativescript-platform-css#8]
The platform-css plugin does not work anymore. The app crashes on start time and shows the error message _nsPlatform.screen is not a function_ on both Android and iOS. We are still using the same version of the plugin (1.5.0) in our NS 2.5 branch and our NS 3 branch as we did the weeks before and suddenly this error occurs.

Please tell me if you need more detailed information to find the cause of this issue.

Thanks in advance.

**Comment by NathanaelA** [comment]
Sorry about that; I just updated the ns-platform plugin late last week, and the platform-css will be upgraded shortly to take advantage of the new features in it.  But the `screen` was changed to be a property rather than a function to make it easier to use.   If you want you can pin your ns-platform to the older version, and use it currently; or just wait a day or so for the new `-css` release.

**Comment by NathanaelA** [comment]
The new version has been released.  Sorry for breaking it.

**Comment by felix-idf** [comment]
It's working, thank you very much!
